name:               "Stratosphere | Next Generation Big Data Processing"
markdown:           redcarpet
highlighter:        pygments
timezone:           "Europe/Berlin"
safe:               true
lsi:                false

# pagination
paginate:           10
paginate_path:      "blog/page-:num"

# see https://github.com/mojombo/jekyll/issues/332
baseurl:            ""

# Stratosphere related variables
current_snapshot:       "0.6-SNAPSHOT"
current_snapshot_yarn:  "0.6-hadoop2-SNAPSHOT"
current_stable:         "0.5.2"
current_stable_yarn:    "0.5.2-hadoop2"
#used in download and quickstart

current_stable_dl:      "https://github.com/stratosphere/stratosphere/releases/download/release-0.5.2/stratosphere-0.5.2-bin.tgz"
current_stable_dl_yarn: "https://github.com/stratosphere/stratosphere/releases/download/release-0.5.2/stratosphere-0.5.2-hadoop2-bin.tgz"
current_stable_uberjar: "https://github.com/stratosphere/stratosphere/releases/download/release-0.5.2/stratosphere-0.5.2-yarn.tar.gz"
current_stable_sopremo: "https://github.com/stratosphere/stratosphere-sopremo/releases/download/release-0.4/sopremo-meteor-dist-0.4-bin.tar.gz"
current_stable_documentation: "0.5"

docs_05_stable: "0.5"
docs_05_stable_gh_tag: "release-0.5"
docs_05_yarn_archive: "https://github.com/stratosphere/stratosphere/releases/download/release-0.5.2/stratosphere-0.5.2-yarn.tar.gz"
